"""
autonomous_engine/agents/validator_auto.py — Lint/tests before push

For each PR generated by fixer_swarm:
  1. Run repo's own lint (npm run lint / pylint / ruff / go vet / cargo check)
  2. Run repo's own tests (npm test / pytest / cargo test)
  3. If FAIL → block push, log to worklog
  4. If PASS → allow fixer_swarm to push

Goal: 0 rejections from maintainer review.
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

ENGINE_HOME = Path(__file__).resolve().parent.parent
STATE_FILE = ENGINE_HOME / "state" / "validator_auto.json"

# Common validation commands per language
VALIDATORS = {
    "node": ["npm run lint", "npm test"],
    "python": ["ruff check .", "pytest"],
    "go": ["go vet ./...", "go test ./..."],
    "rust": ["cargo check", "cargo test"],
}


def load_state() -> dict:
    if STATE_FILE.exists():
        try:
            with open(STATE_FILE) as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            pass
    return {
        "last_run_at": None,
        "validations_run": 0,
        "validations_passed": 0,
        "validations_blocked": 0,
        "events": [],
    }


def save_state(state: dict) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2, ensure_ascii=False)


def detect_language(repo_path: Path) -> str | None:
    """Detect repo language from package files."""
    if (repo_path / "package.json").exists():
        return "node"
    if (repo_path / "pyproject.toml").exists() or (repo_path / "requirements.txt").exists():
        return "python"
    if (repo_path / "go.mod").exists():
        return "go"
    if (repo_path / "Cargo.toml").exists():
        return "rust"
    return None


def run_validations(repo_path: Path) -> dict:
    """Run language-appropriate validations."""
    lang = detect_language(repo_path)
    if lang is None:
        return {"status": "skip", "reason": "Unknown language"}

    commands = VALIDATORS.get(lang, [])
    results = []
    for cmd in commands:
        try:
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True,
                timeout=120, cwd=str(repo_path),
            )
            results.append({
                "command": cmd,
                "returncode": result.returncode,
                "stdout": result.stdout[-500:],
                "stderr": result.stderr[-500:],
                "passed": result.returncode == 0,
            })
        except subprocess.TimeoutExpired:
            results.append({
                "command": cmd,
                "returncode": -1,
                "error": "TIMEOUT after 120s",
                "passed": False,
            })
        except Exception as e:
            results.append({
                "command": cmd,
                "returncode": -1,
                "error": str(e)[:200],
                "passed": False,
            })

    all_passed = all(r.get("passed") for r in results)
    return {
        "language": lang,
        "results": results,
        "all_passed": all_passed,
    }


def run_cycle() -> dict:
    """Stub — full implementation pending fixer_swarm task queue."""
    print(f"[Validator-Auto] Cycle start at {datetime.now(timezone.utc).isoformat()}")
    state = load_state()
    state["last_run_at"] = datetime.now(timezone.utc).isoformat()
    save_state(state)

    # For now, just check that the validator module loads
    print(f"[Validator-Auto] Stub mode — no fixer_swarm tasks to validate")
    print(f"[Validator-Auto] Validations run: {state.get('validations_run', 0)}")
    print(f"[Validator-Auto] Validations passed: {state.get('validations_passed', 0)}")

    return {
        "status": "stub",
        "queue_size": 0,
        "note": "Will validate fixer_swarm PRs when Ollama is integrated",
    }


if __name__ == "__main__":
    result = run_cycle()
    print(f"\n[Validator-Auto] Cycle result: {result}")
    sys.exit(0)
